### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AntaiIphone**
Added "Innovative Bioresearch" DeSci project as well as their latest 2024 peer reviewed publication on Springer-Nature on blockchain based biomedical data storage in the list of DeSci publications

### CODE REVIEW

**Comment by gingerheart86** [comment]
Thanks for your contribution! @AntaiIphone 
Would you please change Italy per Europe? and insert the citation in alphabetic order?

**Comment by gingerheart86** [comment]
Hello @AntaiIphone would you please put **Fior** J. citation below Ducree's?

**Comment by AntaiIphone** [comment]
Ok. Done. As a suggestion, in the future please consider cronological order instead of alphabetical order, to show the most recent articles on top.

**Comment by gingerheart86** [comment]
@AntaiIphone we could list them chronologically in the first layer of order, then alphabetically. 
Would you like to include that modification?
Thanks!

**Comment by AntaiIphone** [comment]
> @AntaiIphone we could list them chronologically in the first layer of order, then alphabetically. Would you like to include that modification? Thanks!

Given that it is taking months just to include such a simple change, let's first approve it in its current state. So we can add the updated info to the database. And let's be that as a part of a future request, eventually.

**Review by AntaiIphone — COMMENTED** [review]
please let's approve.

**Comment by gingerheart86** [comment]
@AntaiIphone the notification got lost.
Agree, let's do that

**Pull request merged**
