### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by flowscience**
add OpenCann + BanklessDeSci
rm Cannabis Genome DAO

### CODE REVIEW

**Comment by gingerheart86** [comment]
Hey Elijah!

I believe we can take the opportunity to update DSW dashboard with opencann information. 
The linked you added is from Cannabis Genomes DAO.

https://cutt.ly/RHCFQIh

Plz remove this link from OpenCann entry 

https://desci.world/project/637473206ef6dbcf1d58884d so I can merge the PR.

We can add the new one once  OpenCann  it's live on our dashboard.


Jelani told me you'd be interested in co-manage our repository. That would be awesome!
We are migrating it to GOSH.
Maybe we can set up a call soon and talk about it.
In the meantime we can work here.
I was hoping to add your list of funding resources.
Love to hear your thoughts about it.

Hope you are ok!
All the best!
Caro.

**Comment by flowscience** [comment]
Hi Caro! Thanks for pointing out the ambiguity here. 

OpenCann is Cannabis Genome DAO. Same project but with a new name. I figured the link to the project on the desci world dashboard would stay the same so I left it in there to maintain page history for SEO. Should the content for our project be updated, or would we actually want to delete it and make a new page?

**Comment by gingerheart86** [comment]
Hey Elijah! 
I just updated the name.
Plz check it out at: https://desci.world/project/637473206ef6dbcf1d58884d

**Comment by flowscience** [comment]
> Hey Elijah! 
> I just updated the name.
> Plz check it out at: https://desci.world/project/637473206ef6dbcf1d58884d
> 

Great, thanks! I can submit more updated project details too (description etc).

**Pull request merged**
